### ISSUE TITLE
Collecting Cache Data

### ISSUE THREAD

**Issue by jlousada315** [mtreinish/ciml#49] opened 2020-02-24 12:27 UTC
From logstack.openstack.org, I find an available build_name, for example , tempest-full-py3. 

After running:
ciml-cache-data --build-name tempest-full-py3 --db-uri mysql+pymysql://query:query@logstash.openstack.org/subunit2sql

and I get:
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

What is the command I need to run before the first one ?  or what am I doing wrong? 

I get that I need to connect to the DB, but from the README file, I thought running ciml-cache-data would be enough to have the .zip file

**Comment by kwulffert** [comment] 2020-03-05 11:59
I believe this issue is a duplicate of #53. Is it ok to close the issue now?

**Closed as completed** 2020-03-05 13:31 UTC
